apiVersion: v1
kind: Secret
metadata:
  name: repo-github-giovany79
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/giovany79/argo-rollout.git
  insecure: "true"